"""add confirmed on User?

Revision ID: 5cbcdfd62b77
Revises: 59b1e1071128
Create Date: 2020-12-15 18:34:44.025600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cbcdfd62b77'
down_revision = '59b1e1071128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
